"""initial

Revision ID: c14bc5589997
Revises: 
Create Date: 2026-04-18 11:26:45.043273

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy  # noqa — needed for Vector column type

# revision identifiers, used by Alembic.
revision = 'c14bc5589997'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('face_identities',
    sa.Column('grab_id', sa.UUID(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('grab_id')
    )
    op.create_table('images',
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_name', sa.Text(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('image_id'),
    sa.UniqueConstraint('file_path')
    )
    op.create_table('image_faces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.Column('grab_id', sa.UUID(), nullable=False),
    sa.Column('bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['grab_id'], ['face_identities.grab_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['image_id'], ['images.image_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_id', 'grab_id', name='uq_image_face')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_faces')
    op.drop_table('images')
    op.drop_table('face_identities')
    # ### end Alembic commands ###
